version: '3.7'

services:
  reverse-proxy:
    image: traefik:latest
    container_name: traefik
    security_opt:
      - no-new-privileges:true
    restart: always

    command: 
      - --api.insecure=true
      # - --api.secure=true
      - --log.level=DEBUG
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      - --providers.docker.watch=true
      - --providers.docker.useBindPortIP=true
      - --providers.docker.allowEmptyServices=true
      - --providers.docker.network=traefik

      # switch to using docker swarm
      - --providers.docker.swarmMode=true

      # entrypoints configuration
      - --entrypoints.webinsecure.address=:80
      - --entrypoints.websecure.address=:443

    ports:
      # The HTTP port
      - 80:80
      - 443:443
      # The Web UI (enabled by --api.insecure=true)
      - 8080:8080

    labels:
      traefik.enable: true
      traefik.http.middlewares.test-compress.compress: true

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

    networks:
      - traefik

  # switch to a service
  grizzy-main:
    image: sololearner00262/grizzy-deploy-main:latest

    networks:
      - traefik

    deploy:
      labels:
        traefik.enable: true
        traefik.http.routers.grizzy-deploy.rule: Host(`deploy.grizzy-deploy.com`)
        traefik.http.services.grizzy-deploy.loadbalancer.server.port: 3000

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  # not exposed to traefik but listens for events from cloudAMQP
  grizzy-consumer:
    image: sololearner00262/grizzy-deploy-consumer:latest

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  traefik:
    name: traefik