version: '3'

services:
  reverse-proxy:
    # The official v2 Traefik docker image
    image: traefik:v2.10
    # Enables the web UI and tells Traefik to listen to docker
    command: 
      # - --api.insecure=true 
      - --providers.docker
      - --providers.docker.exposedbydefault=false
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      # - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

    networks:
      - default

  grizzy-deploy:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grizzy-deploy.rule=Host(`deploy.grizzy-deploy.com`)"
      - "traefik.http.routers.grizzy-deploy.entrypoints=web"
      - "traefik.http.routers.grizzy-deploy.service=grizzy-deploy"
      - "traefik.http.services.grizzy-deploy.loadbalancer.server.port=3002"
      - "traefik.http.services.grizzy-deploy.loadbalancer.server.scheme=http"
      - "traefik.http.services.grizzy-deploy.loadbalancer.server.passhostheader=true"

networks:
  default:
    name: traefik